### ISSUE TITLE
Problems with spaces in Makefile on old GNU make

### ISSUE THREAD

**Issue by alanorth** [DataDrake/cuppa#1]
Not critical, but I was just trying to build Cuppa on macOS and get an error:

```
$ make
Makefile:19: *** missing separator.  Stop.
```

The default make version in macOS 10.12 Sierra is `GNU Make 3.81`. I installed a newer make from Homebrew and the project compiles fine with the spaces, but it might be worth mentioning in the README.md that a newer GNU Make is needed, or switching to using tabs?

**Comment by DataDrake** [comment]
Ah, yeah that was just me being too lazy to fix my nanorc for Makefiles. Should be fixed with https://github.com/DataDrake/cuppa/commit/9178a40338a57d632f76d56062110e39847d2e89

Let me know if I missed something!

**Comment by alanorth** [comment]
Yes. Works now, thanks! I heard about cuppa in this week's [this week in Solus](https://solus-project.com/2017/04/24/this-week-in-solus-install-43/) and just wanted to try it.
