### ISSUE TITLE
cuppa finds older releases

### ISSUE THREAD

**Issue by JagdCake** [DataDrake/cuppa#11]
Both `cuppa quick` and `cuppa latest` find the same older releases.

![timewarrior](https://user-images.githubusercontent.com/28141754/50570980-e63cfe80-0da6-11e9-9d2c-a4aee94aaa48.png)

This is the latest timewarrior release — `https://github.com/GothenburgBitFactory/timewarrior/archive/v1.1.1.tar.gz`. Post111ToMaster seems to be the first release from Feb 4, 2018, the same day 1.1.1 was released.

![ansible](https://user-images.githubusercontent.com/28141754/50570981-e89f5880-0da6-11e9-8181-6b4191056bf8.png)

Here, `https://github.com/ansible/ansible/archive/v2.7.5.tar.gz` is the last one. What cuppa found is much older — <https://github.com/ansible/ansible/releases?after=v2.1.4.0-0.2.rc2> but it's under [/releases/latest](https://github.com/ansible/ansible/releases/latest). Coincidentally, I found that the official Ansible releases can be found here — <https://releases.ansible.com/ansible/>, but cuppa doesn't work on <https://releases.ansible.com/ansible/ansible-2.7.5.tar.gz>

**Comment by DataDrake** [comment]
Yeah GitHub support is a bit messed up at the moment. There are a few oddities with the v4 API that I'm still working out.

For the record, it would never work with https://releases.ansible.com/ansible/ansible-2.7.5.tar.gz since I focus on starting from a URL that is close to one that Cuppa would give you.

**Comment by DataDrake** [comment]
I've fixed ansible in master, but timewarrior is going to be a goofy one.
