### ISSUE TITLE
Bad list of release with GNU

### ISSUE THREAD

**Issue by Urgau** [DataDrake/cuppa#12]
There is a listing error when using GNU. The list of release is making by using the order the FTP but the order is false because the FTP sort filenames by characters and not by version so the version 1.9 is greater than 1.20 but this comparison is false for cuppa who need to have 1.9 then 1.20.

Example **cuppa latest https://ftp.gnu.org/gnu/wget/wget-1.20.tar.gz**: 
Give this :
> Name      : wget
> Version   : 1.9.1
> Location  : https://mirrors.rit.edu/gnu/wget/wget-1.9.1.tar.gz
> Published : 2003-11-14T00:00:00Z

Instead of:
> Name      : wget
> Version   : 1.20.1
> Location  : https://mirrors.rit.edu/gnu/wget/wget-1.20.1.tar.lz
> Published : 2018-12-26T20:13:00Z

I think you should sort the list of release by date to fix this issue (and as a precaution do it for all other providers to avoid future problems).

**Comment by DataDrake** [comment]
I don't want to exclusively rely on dates because they are often very wrong. Example: someone uploads a new version of an old archive after a file gets corrupted.

Really I need to port the Version code from `ypkg-update-checker` to this and use that instead.
