### ISSUE TITLE
GitHub links return fatal error

### ISSUE THREAD

**Issue by abdulocracy** [DataDrake/cuppa#13]
For the past few weeks GitHub links have not been working with cuppa.

An example command and output:

```
cuppa q https://github.com/zsh-users/zsh-autosuggestions/archive/v0.5.0.tar.gz
 🕱  10:47:05  FATAL    No release found.
```

**Comment by DataDrake** [comment]
```
 bryan   master  …  github  DataDrake  cuppa  cuppa q https://github.com/zsh-users/zsh-autosuggestions/archive/v0.5.0.tar.gz
0.5.2 https://github.com/zsh-users/zsh-autosuggestions/archive/v0.5.2.tar.gz
```
Working fine for me...

Did you follow these instructions for github? https://github.com/DataDrake/cuppa/blob/master/README.md#github-personal-access-keys

**Comment by abdulocracy** [comment]
Ah sorry, I had it set up on my previous Solus installation, forgot after a clean install. Thanks for the awesome tool! 🙂

**Comment by DataDrake** [comment]
Cheers.
