### ISSUE TITLE
Current build fails

### ISSUE THREAD

**Issue by maxice8** [DataDrake/cuppa#14]
Trying to package it for alpine using upstream instructions leads to.

```
 ⮞  16:56:27  BUILD  
cuppa.go:20:2: cannot find package "github.com/DataDrake/cuppa/cli" in any of:
	/usr/lib/go/src/github.com/DataDrake/cuppa/cli (from $GOROOT)
	/home/impreza/usr/src/aports/testing/cuppa/src/src/github.com/DataDrake/cuppa/cli (from $GOPATH)
make: *** [Makefile:29: build] Error 1
>>> ERROR: cuppa: build failed
```

**Comment by DataDrake** [comment]
I can't reproduce this. Are you building from master or a tagged release? v1.0.4 is broken and I need to tweak a few things before I release v1.1.0.

**Comment by maxice8** [comment]
building from current commit  that is in master

**Comment by DataDrake** [comment]
Can you try with GOPATH cleared and let me know what version of Go you are using?

**Comment by DataDrake** [comment]
I'm going to close this since I've waited over a year for an answer.
