### ISSUE TITLE
Usage Instructions/Examples

### ISSUE THREAD

**Issue by chetgurevitch** [DataDrake/cuppa#2]
I'd like to use cuppa to help track versions for some PKGBUILD files but when I run `cuppa releases https://github.com/neovim/neovim` for example none of the providers return a match and no releases are found.

It's not very clear how the program is intended to be used. Am I just formatting the command wrong, is it supposed to be run against build files, if so would changes be required for different packaging formats, etc.

**Comment by DataDrake** [comment]
Yeah, I'm working through a CLI library to do better help text and things. I'll also be adding API key support for Github so you don't get rate limited to ~1000 API calls per day.

As for your immediate issue, `cuppa` expects the full URL for the location of an existing tarball. For example:

```
https://github.com/neovim/neovim/archive/v0.2.0.tar.gz
```

I'll leave this open until the new help system is in place.

**Comment by chetgurevitch** [comment]
Thanks, just figured that out lol. Everything seems to be working fine.

**Comment by DataDrake** [comment]
This was actually resolved a few days ago, but I'm going to keep it open until I add examples to the README.
