### ISSUE TITLE
Support for ypkg package.yml files

### ISSUE THREAD

**Issue by FSMaxB** [DataDrake/cuppa#3]
It would be great if a package.yml file could just be passed as a parameter to cuppa and it would automatically use the first source file to search for new versions.

**Comment by DataDrake** [comment]
Not going to support that. The point of Cuppa is to be agnostic, not to have special bits for different things (ie. OS, package manager). When I integrate Cuppa as a library for ypkg, there will be no need.

**Comment by FSMaxB** [comment]
The other way around sounds great. Integrating cuppa into ypkg instead of the other way around.
