### ISSUE TITLE
Potential corner cases in GitHub lookup

### ISSUE THREAD

**Issue by sunnyflunk** [DataDrake/cuppa#5]
As promised, here's some examples from the report of some odd results. Tbh, they might be issues with how the authors mark the releases, but are worth a look.

```
ibus-libzhuyin 1.7.10  https://github.com/epico/ibus-libzhuyin/archive/.tar.gz
mate-menu 18.04.3 16.10.1 https://github.com/ubuntu-mate/mate-menu/archive/16.10.1.tar.gz
naev 0.7.0 NAEV-0.3.8 https://github.com/naev/naev/archive/NAEV-0.3.8.tar.gz
flare-engine 1.06 1.0 https://github.com/clintbellanger/flare-engine/archive/v1.0.tar.gz
neovim-qt 0.2.8  https://github.com/equalsraf/neovim-qt/archive/staging.tar.gz
numix-icon-theme 17.12.25  https://github.com/numixproject/numix-icon-theme/archive/.tar.gz
numix-icon-theme-circle 18.04.04  https://github.com/numixproject/numix-icon-theme-circle/archive/.tar.gz
numix-icon-theme-square 18.04.04  https://github.com/numixproject/numix-icon-theme-square/archive/.tar.gz
```

**Comment by DataDrake** [comment]
Keep track as list:
- [x] ibus-libzhuyin 1.8.92 https://github.com/epico/ibus-libzhuyin/archive/1.8.92.tar.gz
- [x] mate-menu 18.04.3 https://github.com/ubuntu-mate/mate-menu/archive/18.04.3.tar.gz
- [x] naev naev-0.7.0 https://github.com/naev/naev/archive/naev-0.7.0.tar.gz
- [ ] flare-engine 1.06 1.0 https://github.com/clintbellanger/flare-engine/archive/v1.0.tar.gz
- [ ] neovim-qt 0.2.8  https://github.com/equalsraf/neovim-qt/archive/staging.tar.gz
- [x] numix-icon-theme 18.07.17 https://github.com/numixproject/numix-icon-theme/archive/18.07.17.tar.gz
- [x] numix-icon-theme-circle 18.08.01 https://github.com/numixproject/numix-icon-theme-circle/archive/18.08.01.tar.gz
- [x] numix-icon-theme-square 18.08.01 https://github.com/numixproject/numix-icon-theme-square/archive/18.08.01.tar.gz

**Comment by DataDrake** [comment]
`flare-engine` has newer tags than releases, so I'll need to work around that.
`neovim-qt` has the same problem.

**Comment by DataDrake** [comment]
Looks like I've fixed the last two.
