### ISSUE TITLE
Suggested additional providers

### ISSUE THREAD

**Issue by ObscureScience** [DataDrake/cuppa#7]
I'm not sure if you want such suggestions here. But if so, I would like to point out the ["Free Software Directory"](https://directory.fsf.org/wiki/Main_Page) as an important one. In particular packages under [gnu.org/software](https://www.gnu.org/software/). Feel free to add to this list if deemed appropriate.

**Comment by DataDrake** [comment]
TL;DR the goal of cuppa is to rely on APIs for two reasons:

1. It minimizes the traffic impact on the respective provider
2. It minimizes the need to rely on typically unreliable web-scraping.

Additionally, I'd like to point out that GNU software can easily be tracked from Git in most cases.
