### ISSUE TITLE
erroneous cpan results

### ISSUE THREAD

**Issue by simbiotiqu** [DataDrake/cuppa#8]
Tested cuppa, version: 1.0.4 on some cpan links.

**Returns: code1**

`cuppa l https://cpan.metacpan.org/authors/id/R/RG/RGARCIA/Sub-Identify-0.14.tar.gz`

Returns:

```
 ⮞  CPAN checking for match:
 🗲  Could not get latest Sub, code: 1
```

------------

**Returns first result**

`cuppa l https://cpan.metacpan.org/authors/id/D/DO/DOY/Package-Stash-0.37.tar.gz`

returns 

```
Name      : Package
Version   : 0.26
Location  : https://cpan.metacpan.org/authors/id/I/IN/INGY/Package-0.26.tar.gz
```

Seems to grab the first result 'Package-...' it can find. 
Should return:
```
Name      : Package-Stash
Version   : 0.37
Location  : https://cpan.metacpan.org/authors/id/D/DO/DOY/Package-Stash-0.37.tar.gz
```

Same behavior for:
'https://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/Test-Requires-0.10.tar.gz'
'https://cpan.metacpan.org/authors/id/E/ET/ETHER/namespace-autoclean-0.28.tar.gz'
'https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Locale-1.22.tar.gz'

**Comment by DataDrake** [comment]
So basically anything with a hyphen in the name.
