### ISSUE TITLE
Usage and configuration examples

### ISSUE THREAD

**Issue by alanorth** [DataDrake/cuppa#9]
I found it a bit tricky to configure and run cuppa. It would be nice if you could add a few examples to the readme to get users started:

- How to build (install golang and run `make`)
- How run cuppa (ie, example command lines of some source releases that work)
- Location of config file (I got the location via reading the code in `config/config.go`)

Also, is it possible to have a sort of configuration where you list the projects and versions you're using, or are you supposed to run cuppa in a loop in a shell script? For example, something like this in the `~/.config/cuppa` config file:

```
[projects]
restic 0.9.2 https://github.com/restic/restic/releases/download/v0.9.2/restic-0.9.2.tar.gz
```

**Comment by DataDrake** [comment]
I mean your first three bullet points are all currently covered about half way through the README.md

Cuppa is designed to be run for a single source, one at a time. If you want something that does multiple, it can easily be integrated into another Go application as a library. This was how I implemented it for [ypkg-update-checker](https://github.com/DataDrake/ypkg-update-checker). The sole purpose of the config file is to configure the operation of Cuppa, not for specifying sources. That isn't going to change.

I might be open to a proposal for another sub-command which reads in a file for checking multiple sources, but I don't see the point in listing the version numbers in that file. Cuppa is intended for getting the **latest** version of software, not dependency management.

**Comment by alanorth** [comment]
Oh crap. That's a bit embarrassing. My local git checkout was up to date but I was not on the latest `origin/master`. I see the build instructions and config instructions now. :sweat_smile:

Point taken about the multiple sources. Thanks!
